# Configure taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "johanhaleby/kubetail"
# Configure where our applications go
cask_args appdir: "/Applications"

brew "bash"
brew "bash-completion@2"
brew "coreutils"
brew "curl"
brew "findutils"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "go"
brew "grep"
brew "htop"
brew "jq"
brew "kubectx"
brew "kubernetes-cli"
brew "kubetail"
brew "mas"
brew "maven"
brew "maven-completion"
brew "moreutils"
brew "netcat"
brew "node"
brew "ssh-copy-id"
brew "starship"
brew "stow"
brew "vim"
brew "wget"
brew "yarn"
brew "yarn-completion"
brew "yq"

cask "adobe-acrobat-reader"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "jetbrains-toolbox"
cask "keepassxc"
cask "rectangle"
cask "sourcetree"
cask "the-unarchiver"
cask "visual-studio-code"
cask "temurin"
