#!/usr/bin/env bash
# the shebang statement above is only here to allow linting this file

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in "${HOME}/.config/bash/"{exports,path,aliases,functions,extra}; do
	[[ -r "${file}" ]] && [[ -f "${file}" ]] && source "${file}"
done
unset file
[[ -r "${HOME}/.extra" ]] && [[ -f "${HOME}/.extra" ]] && source "${HOME}/.extra"

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# check the window size after each command and, if necessary, update the values of LINES and COLUMNS
shopt -s checkwinsize

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
	shopt -s "${option}" 2>/dev/null
done

# Add tab completion for many Bash commands
# This will automatically source the bash_completion file in dot-config as well
if [[ -n "${BREW_PREFIX}" ]]; then
	if [[ -f "${BREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
		source "${BREW_PREFIX}/etc/profile.d/bash_completion.sh"
	fi
fi

# Launch Starship as prompt: https://starship.rs/
eval "$(starship init bash)"
