#!/usr/bin/env bash
# the shebang statement above is only here to allow linting this file

# verify necessary path adjustments against the caveats from brew (accessible from 'brew info $(brew list)')
# as well as the output of 'brew shellenv'
if sysctl -n machdep.cpu.brand_string | grep -q 'Intel' ; then
	export PATH="/usr/local/sbin:${PATH}"

	export PATH="/usr/local/opt/coreutils/libexec/gnubin:${PATH}"
	export PATH="/usr/local/opt/curl/bin:${PATH}"
	export PATH="/usr/local/opt/findutils/libexec/gnubin:${PATH}"
	export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:${PATH}"
	export PATH="/usr/local/opt/grep/libexec/gnubin:${PATH}"

	export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:${MANPATH}"
	export MANPATH="/usr/local/opt/curl/share/man:${MANPATH}"
	export MANPATH="/usr/local/opt/findutils/libexec/gnuman:${MANPATH}"
	export MANPATH="/usr/local/opt/gnu-sed/libexec/gnuman:${MANPATH}"
	export MANPATH="/usr/local/opt/grep/libexec/gnuman:${MANPATH}"
else
	export PATH="/opt/homebrew/bin:${PATH}"

	export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:${PATH}"
	export PATH="/opt/homebrew/opt/curl/bin:${PATH}"
	export PATH="/opt/homebrew/opt/findutils/libexec/gnubin:${PATH}"
	export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:${PATH}"
	export PATH="/opt/homebrew/opt/grep/libexec/gnubin:${PATH}"

	export MANPATH="/opt/homebrew/opt/coreutils/libexec/gnuman:${MANPATH}"
	export MANPATH="/opt/homebrew/opt/curl/share/man:${MANPATH}"
	export MANPATH="/opt/homebrew/opt/findutils/libexec/gnuman:${MANPATH}"
	export MANPATH="/opt/homebrew/opt/gnu-sed/libexec/gnuman:${MANPATH}"
	export MANPATH="/opt/homebrew/opt/grep/libexec/gnuman:${MANPATH}"
fi
