#!/usr/bin/env bash
# the shebang statement above is only here to allow linting this file

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{path,exports,aliases,functions,extra}; do
	[[ -r "${file}" ]] && [[ -f "${file}" ]] && source "${file}"
done
unset file

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
	shopt -s "${option}" 2>/dev/null
done

# Add tab completion for many Bash commands
if type brew &>/dev/null; then
	brew_prefix=$(brew --prefix)
	if [[ -f "${brew_prefix}/etc/profile.d/bash_completion.sh" ]]; then
		source "${brew_prefix}/etc/profile.d/bash_completion.sh"
	fi
	unset brew_prefix
fi

# Add tab completion for Docker
if [[ -d "/Applications/Docker.app/Contents/Resources/etc/" ]]; then
	source "/Applications/Docker.app/Contents/Resources/etc/docker.bash-completion"
	source "/Applications/Docker.app/Contents/Resources/etc/docker-compose.bash-completion"
fi

# Enable tab completion for `g` by marking it as an alias for `git`
if type __git_complete &>/dev/null; then
	__git_complete g __git_main
fi

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[[ -r "${HOME}/.ssh/config" ]] && [[ -f "${HOME}/.ssh/config" ]] &&
	complete -o "default" -o "nospace" -W "$(grep -R "^Host " "${HOME}/.ssh" |
		cut -d " " -f2- | tr ' ' '\n' | grep -v "[!?*]" | sort | uniq)" scp sftp ssh

# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults

# Add `killall` tab completion for common apps
complete -o "nospace" -W "Contacts Calendar Dock Finder Mail Safari iTunes SystemUIServer Terminal" killall

# Launch Starship as prompt: https://starship.rs/
eval "$(starship init bash)"
