#!/usr/bin/env bash
# the shebang statement above is only here to allow linting this file

# This ensures that on Mac with ARMs / Apple Silicon the ble.sh integration
# works as expected because we install it from brew
# loading path & exports first doesn't work because coreutils are being used
# and that will overwrite /bin/stty as well
# See https://github.com/akinomyoga/ble.sh/issues/63
BREW_PREFIX="/opt/homebrew"
if sysctl -n machdep.cpu.brand_string | grep -q 'Intel'; then
	BREW_PREFIX="/usr/local"
fi

# Add ble.sha as Bash line editor: https://github.com/akinomyoga/ble.sh
if [[ -f "${BREW_PREFIX}/opt/blesh/share/blesh/ble.sh" ]]; then
	[[ $- == *i* ]] && source "${BREW_PREFIX}/opt/blesh/share/blesh/ble.sh" --attach=none
fi
unset BREW_PREFIX

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in "${HOME}/.config/bash/"{path,exports,aliases,functions,extra}; do
	[[ -r "${file}" ]] && [[ -f "${file}" ]] && source "${file}"
done
unset file
[[ -r "${HOME}/.extra" ]] && [[ -f "${HOME}/.extra" ]] && source "${HOME}/.extra"

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# check the window size after each command and, if necessary, update the values of LINES and COLUMNS
shopt -s checkwinsize

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
	shopt -s "${option}" 2>/dev/null
done

# Add tab completion for many Bash commands. This will automatically source the bash_completion file in dot-config as well
if [[ -n "${BREW_PREFIX}" ]] && [[ -f "${BREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
	source "${BREW_PREFIX}/etc/profile.d/bash_completion.sh"
fi

# Launch Starship as prompt: https://starship.rs/
eval "$(starship init bash)"
if [[ -f "${BREW_PREFIX}/opt/blesh/share/blesh/ble.sh" ]]; then
	# Add Atuin as history replacement: https://atuin.sh/
	eval "$(atuin init bash)"
	# Add ble.sha as Bash line editor: https://github.com/akinomyoga/ble.sh
	[[ ! ${BLE_VERSION-} ]] || ble-attach
fi
