#!/usr/bin/env bash
# shellcheck disable=SC2154

# Set up XDG Base Directory Specifications for more a consistent dotfile experience between macOS and Linux
# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"

# Make vim the default editor.
export EDITOR='vim'

# Enable persistent REPL history for `node`.
export NODE_REPL_HISTORY="${XDG_DATA_HOME}/node/history"
# Allow 32³ entries; the default is 1000.
export NODE_REPL_HISTORY_SIZE='32768'
# Use sloppy mode by default, matching web browsers.
export NODE_REPL_MODE='sloppy'

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8'

# Make Ruby use the XDG cache directory for gem installations
# https://www.moncefbelyamani.com/the-definitive-guide-to-installing-ruby-gems-on-a-mac/
export GEM_HOME="${XDG_CACHE_HOME}/ruby/gem"

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768'
export HISTFILE="${XDG_CACHE_HOME}/bash/history"
export HISTFILESIZE="${HISTSIZE}"
# Omit duplicates and commands that begin with a space from history. Also delete duplicates from the history.
export HISTCONTROL='ignoreboth:erasedups'

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# Don’t clear the screen after quitting a manual page.
#export MANPAGER='less -X';

# Use bat as pager
# https://github.com/sharkdp/bat#man
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
GPG_TTY=$(tty)
export GPG_TTY

# Hide the “default interactive shell is now zsh” warning on macOS.
export BASH_SILENCE_DEPRECATION_WARNING=1

# Make vim XDG Base Directory Specification aware
# shellcheck disable=SC2016
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'

if command -v brew >/dev/null; then
	BREW_PREFIX=$(brew --prefix)
	export BREW_PREFIX
fi

# Make screen XDG aware
export SCREENRC="${XDG_CONFIG_HOME}/screenrc"

# Make Go XDG aware
export GOPATH="${XDG_DATA_HOME}/go"
export GOMODCACHE="${XDG_CACHE_HOME}/go/mod"

# Make wget XDG aware
export WGETRC="${XDG_CONFIG_HOME}/wgetrc"

# Make ripgrep XDF aware
export RIPGREP_CONFIG_PATH="${XDG_CONFIG_HOME}/ripgreprc"
