#!/usr/bin/env bash
# the shebang statement above is only here to allow linting this file

# Add tab completion for Docker and Docker Compose
if [[ -d "/Applications/Docker.app/Contents/Resources/etc/" ]]; then
	if [[ -f "/Applications/Docker.app/Contents/Resources/etc/docker.bash-completion" ]]; then
		source "/Applications/Docker.app/Contents/Resources/etc/docker.bash-completion"
	fi
	if [[ -f "/Applications/Docker.app/Contents/Resources/etc/docker-compose.bash-completion" ]]; then
		source "/Applications/Docker.app/Contents/Resources/etc/docker-compose.bash-completion"
	fi
fi

# Enable tab completion for `g` by marking it as an alias for `git`
if type __git_complete &>/dev/null; then
	__git_complete g __git_main
fi

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
if [[ -r "${HOME}/.ssh/config" ]] && [[ -f "${HOME}/.ssh/config" ]]; then
	complete -o "default" -o "nospace" -W "$(grep -R "^Host " "${HOME}/.ssh" | cut -d " " -f2- | tr ' ' '\n' | grep -v "[!?*]" | sort | uniq | tr '\n' ' ')" scp sftp ssh
fi

# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults

# Add `killall` tab completion for common apps
complete -o "nospace" -W "Contacts Calendar Dock Finder Mail Safari iTunes SystemUIServer Terminal" killall
